##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://leighbonds.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /mrrc
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: The Mary Robinson Research Companion
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "A digital collection of resources to contribute to Mrs. Robinson's recovery and inspire new areas of research."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: Mary Robinson; Mrs. Robinson; British women writers; Romantic women writers
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Elizabeth Leigh Bonds

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: mrrc_prototype_volumes;mrrc_prototype_portraits;mrrc_prototype_reviews
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
page_gen:
  - data: 'mrrc_prototype_volumes'
  - data: 'mrrc_prototype_portraits'
  - data: 'mrrc_prototype_reviews'

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
